### ISSUE TITLE
arm: Elements Issues

### ISSUE THREAD

**Issue by k-nkmt** [sassoftware/clinical-standards-toolkit#14]
- Duplicate arm:AnalysisResult
When a single ResultIdentifier references multiple datasets and the ParameterColumn is filled in, the arm:AnalysisResult element for the corresponding ResultIdentifier is output repeatedly.

- Optional Elements Always Output
The optional elements arm:Documentation and arm:ProgrammingCode are always created.

**Comment by michaelkilhullen** [comment]
Thanks Chris!Sent from my iPhoneOn Dec 21, 2024, at 1:52 PM, Chris Hemedinger ***@***.***> wrote:﻿
Closed #14 as completed via #15.
