### ISSUE TITLE
cstutilwriteresultsintro

### ISSUE THREAD

**Issue by lexjansen** [sassoftware/clinical-standards-toolkit#3]
When removing unnecessary sysver checks, too much was removed in the cstutilwriteresultsintro macro.
This results in LOG messages:
[CSTLOGMESSAGE.CSTUTILWRITERESULTSINTRO]: Program name could not be determined and has been set to Unspecified

The %else statement needs to be restored in the macro:

    %if %nrbquote(%sysfunc(getoption(SYSIN))) EQ and &sysscp eq WIN
      %then %do;
           %if %sysfunc(sysexist(SAS_EXECFILENAME)) %then %let _cstProgram = %sysget(SAS_EXECFILENAME);
      %end;
      %else %let _cstProgram = %sysfunc(scan(%nrbquote(%sysfunc(getoption(SYSIN))),-1,\));

**Comment by michaelkilhullen** [comment]
fix pushed
