### ISSUE TITLE
define v2.1

### ISSUE THREAD

**Issue by johnmcdade76** [sassoftware/clinical-standards-toolkit#4]
Interested if this could be compatible with generation of define v2.1, happy to help anyway I can.

**Comment by michaelkilhullen** [comment]
We can certainly work on getting it added.  Technically, we can do it.  What I'm looking for from the field is use cases for how you would want to interact with a Define 2.1 file in toolkit.  That is, how to you see identifying what standards are in the define and how would you want to connect them up in metadata\code.  This will help identify macro requirements.  You can add to this issue and hopefully others will chime in as well.

**Comment by lexjansen** [comment]
I am actually very far in having Define-XML 2.1 included in my fork. It will be consistent with the way 2.0 was defined, with an extra source dataset for the standards.

**Comment by johnmcdade76** [comment]
I can see the FDA are making v2.1 a requirement from 15th March 2023, more than happy to help with any testing if a version is available.

**Comment by lexjansen** [comment]
Thanks, @johnmcdade76. Appreciated. I will let you know when the update is available. It took me a bit longer than expected. Btw, 2.0 is still supported as well.
